version: '3'

services:
  web:
    image: ghcr.io/${GITHUB_REPOSITORY:fev125/dstatus}:latest  # 使用 GitHub Container Registry
    container_name: dstatus
    ports:
      - "0.0.0.0:${WEB_PORT:-5555}:5555"      # Web 管理界面端口
    volumes:
      - dstatus-data:/app/database
      - dstatus-logs:/app/logs
    environment:
      - NODE_ENV=production
    restart: unless-stopped  # 添加自动重启策略

volumes:
  dstatus-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/dstatus/database
  dstatus-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/dstatus/logs