version: '3.8'

services:
  web:
    image: ghcr.io/fev125/dstatus:sha-a8d8803  # 使用最新的 SHA 标签
    container_name: dstatus
    ports:
      - "0.0.0.0:${WEB_PORT:-5555}:5555"      # Web 管理界面端口
    volumes:
      - dstatus-data:/app/database
      - dstatus-logs:/app/logs
    environment:
      - NODE_ENV=production
      - TZ=Asia/Shanghai
    restart: unless-stopped  # 添加自动重启策略
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5555"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

volumes:
  dstatus-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/dstatus/database
  dstatus-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/dstatus/logs