version: '3'

services:
  web:
    build: .  # 使用本地代码构建
    container_name: dstatus
    ports:
      - "0.0.0.0:${WEB_PORT:-5555}:5555"      # Web 管理界面端口
    volumes:
      - dstatus-data:/app/database
      - dstatus-logs:/app/logs
    environment:
      - NODE_ENV=production
    restart: unless-stopped  # 添加自动重启策略

volumes:
  dstatus-data:
  dstatus-logs:
