name: Docker Build and Save

on:
  workflow_dispatch:
    inputs:
      version:
        description: '镜像版本号（例如：v1.0.0）'
        required: true
        default: 'latest'

env:
  IMAGE_NAME: my-app

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 步骤 1: 清理 Actions 缓存
      - name: Clean up action cache
        run: |
          sudo rm -rf ~/work/_actions/cache/*

      # 步骤 2: 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 步骤 3: 初始化 Docker 构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 步骤 4: 构建 Docker 镜像
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.event.inputs.version || 'latest' }}

      # 步骤 5: 保存镜像为 .tar 文件
      - name: Save Docker image as .tar
        run: |
          docker save -o ${{ env.IMAGE_NAME }}.tar ${{ env.IMAGE_NAME }}:${{ github.event.inputs.version || 'latest' }}

      # 步骤 6: 上传构建产物（直接使用 v3 标签）
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ${{ env.IMAGE_NAME }}.tar
