name: Docker Build and Save

on:
  # 手动触发
  workflow_dispatch:
    inputs:
      version:
        description: '镜像版本号 (例如: latest)'
        required: true
        default: 'latest'
  # 自动触发条件（可选）
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: my-app # 镜像名称

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read  # 仅需读取仓库权限

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true  # 将镜像加载到本地 Docker
          tags: ${{ env.IMAGE_NAME }}:${{ github.event.inputs.version || 'latest' }}

      - name: Save Docker image as .tar
        run: |
          docker save -o ${{ env.IMAGE_NAME }}.tar ${{ env.IMAGE_NAME }}:${{ github.event.inputs.version || 'latest' }}

      - name: Upload Docker image artifact
        uses: actions/upload-artifact@v3
        with:
          name: docker-image
          path: ${{ env.IMAGE_NAME }}.tar
