name: Docker Build and Save

on:
  workflow_dispatch:
    inputs:
      version:
        description: '镜像版本号（例如：v1.0.0）'
        required: true
        default: 'latest'

env:
  IMAGE_NAME: my-app

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      # 清理缓存
      - name: Clean up action cache
        run: |
          sudo rm -rf ~/work/_actions/cache/*

      # 检出代码
      - name: Checkout repository
        uses: actions/checkout@v3

      # 初始化 Docker 构建环境
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 构建镜像
      - name: Build Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          load: true
          tags: ${{ env.IMAGE_NAME }}:${{ github.event.inputs.version || 'latest' }}

      # 保存为 .tar 文件
      - name: Save Docker image as .tar
        run: |
          docker save -o ${{ env.IMAGE_NAME }}.tar ${{ env.IMAGE_NAME }}:${{ github.event.inputs.version || 'latest' }}

      # 上传构建产物（使用固定 SHA）
      - name: Upload Docker image artifact
        uses: actions/upload-artifact@d5d050df31c4f9b7be50e2f341477a0d7c1096c7
        with:
          name: docker-image
          path: ${{ env.IMAGE_NAME }}.tar
